/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DirectoryRouteImport } from './routes/directory'
import { Route as ChartRouteImport } from './routes/chart'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JobsIndexRouteImport } from './routes/jobs.index'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as JobsSlugRouteImport } from './routes/jobs.$slug'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as EmployeeEmployeeIdRouteImport } from './routes/employee.$employeeId'
import { Route as AdminAdminPeopleRouteImport } from './routes/_admin.admin.people'
import { Route as AdminAdminDashboardRouteImport } from './routes/_admin.admin.dashboard'
import { Route as AdminAdminPeopleIndexRouteImport } from './routes/_admin.admin.people.index'
import { Route as AdminAdminPeopleNewRouteImport } from './routes/_admin.admin.people.new'
import { Route as AdminAdminPeopleEmployeeIdEditRouteImport } from './routes/_admin.admin.people_.$employeeId.edit'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DirectoryRoute = DirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => rootRouteImport,
} as any)
const ChartRoute = ChartRouteImport.update({
  id: '/chart',
  path: '/chart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsIndexRoute = JobsIndexRouteImport.update({
  id: '/jobs/',
  path: '/jobs/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsSlugRoute = JobsSlugRouteImport.update({
  id: '/jobs/$slug',
  path: '/jobs/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployeeEmployeeIdRoute = EmployeeEmployeeIdRouteImport.update({
  id: '/employee/$employeeId',
  path: '/employee/$employeeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminPeopleRoute = AdminAdminPeopleRouteImport.update({
  id: '/admin/people',
  path: '/admin/people',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminPeopleIndexRoute = AdminAdminPeopleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminPeopleRoute,
} as any)
const AdminAdminPeopleNewRoute = AdminAdminPeopleNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminAdminPeopleRoute,
} as any)
const AdminAdminPeopleEmployeeIdEditRoute =
  AdminAdminPeopleEmployeeIdEditRouteImport.update({
    id: '/admin/people_/$employeeId/edit',
    path: '/admin/people/$employeeId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/people': typeof AdminAdminPeopleRouteWithChildren
  '/admin/people/new': typeof AdminAdminPeopleNewRoute
  '/admin/people/': typeof AdminAdminPeopleIndexRoute
  '/admin/people/$employeeId/edit': typeof AdminAdminPeopleEmployeeIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chart': typeof ChartRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/industries': typeof IndustriesIndexRoute
  '/jobs': typeof JobsIndexRoute
  '/admin/dashboard': typeof AdminAdminDashboardRoute
  '/admin/people/new': typeof AdminAdminPeopleNewRoute
  '/admin/people': typeof AdminAdminPeopleIndexRoute
  '/admin/people/$employeeId/edit': typeof AdminAdminPeopleEmployeeIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/chart': typeof ChartRoute
  '/directory': typeof DirectoryRoute
  '/login': typeof LoginRoute
  '/employee/$employeeId': typeof EmployeeEmployeeIdRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/jobs/$slug': typeof JobsSlugRoute
  '/industries/': typeof IndustriesIndexRoute
  '/jobs/': typeof JobsIndexRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardRoute
  '/_admin/admin/people': typeof AdminAdminPeopleRouteWithChildren
  '/_admin/admin/people/new': typeof AdminAdminPeopleNewRoute
  '/_admin/admin/people/': typeof AdminAdminPeopleIndexRoute
  '/_admin/admin/people_/$employeeId/edit': typeof AdminAdminPeopleEmployeeIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chart'
    | '/directory'
    | '/login'
    | '/employee/$employeeId'
    | '/industries/$slug'
    | '/jobs/$slug'
    | '/industries/'
    | '/jobs/'
    | '/admin/dashboard'
    | '/admin/people'
    | '/admin/people/new'
    | '/admin/people/'
    | '/admin/people/$employeeId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chart'
    | '/directory'
    | '/login'
    | '/employee/$employeeId'
    | '/industries/$slug'
    | '/jobs/$slug'
    | '/industries'
    | '/jobs'
    | '/admin/dashboard'
    | '/admin/people/new'
    | '/admin/people'
    | '/admin/people/$employeeId/edit'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/chart'
    | '/directory'
    | '/login'
    | '/employee/$employeeId'
    | '/industries/$slug'
    | '/jobs/$slug'
    | '/industries/'
    | '/jobs/'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/people'
    | '/_admin/admin/people/new'
    | '/_admin/admin/people/'
    | '/_admin/admin/people_/$employeeId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ChartRoute: typeof ChartRoute
  DirectoryRoute: typeof DirectoryRoute
  LoginRoute: typeof LoginRoute
  EmployeeEmployeeIdRoute: typeof EmployeeEmployeeIdRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  JobsSlugRoute: typeof JobsSlugRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  JobsIndexRoute: typeof JobsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/directory': {
      id: '/directory'
      path: '/directory'
      fullPath: '/directory'
      preLoaderRoute: typeof DirectoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chart': {
      id: '/chart'
      path: '/chart'
      fullPath: '/chart'
      preLoaderRoute: typeof ChartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/': {
      id: '/jobs/'
      path: '/jobs'
      fullPath: '/jobs/'
      preLoaderRoute: typeof JobsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs/$slug': {
      id: '/jobs/$slug'
      path: '/jobs/$slug'
      fullPath: '/jobs/$slug'
      preLoaderRoute: typeof JobsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employee/$employeeId': {
      id: '/employee/$employeeId'
      path: '/employee/$employeeId'
      fullPath: '/employee/$employeeId'
      preLoaderRoute: typeof EmployeeEmployeeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/people': {
      id: '/_admin/admin/people'
      path: '/admin/people'
      fullPath: '/admin/people'
      preLoaderRoute: typeof AdminAdminPeopleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/people/': {
      id: '/_admin/admin/people/'
      path: '/'
      fullPath: '/admin/people/'
      preLoaderRoute: typeof AdminAdminPeopleIndexRouteImport
      parentRoute: typeof AdminAdminPeopleRoute
    }
    '/_admin/admin/people/new': {
      id: '/_admin/admin/people/new'
      path: '/new'
      fullPath: '/admin/people/new'
      preLoaderRoute: typeof AdminAdminPeopleNewRouteImport
      parentRoute: typeof AdminAdminPeopleRoute
    }
    '/_admin/admin/people_/$employeeId/edit': {
      id: '/_admin/admin/people_/$employeeId/edit'
      path: '/admin/people/$employeeId/edit'
      fullPath: '/admin/people/$employeeId/edit'
      preLoaderRoute: typeof AdminAdminPeopleEmployeeIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminAdminPeopleRouteChildren {
  AdminAdminPeopleNewRoute: typeof AdminAdminPeopleNewRoute
  AdminAdminPeopleIndexRoute: typeof AdminAdminPeopleIndexRoute
}

const AdminAdminPeopleRouteChildren: AdminAdminPeopleRouteChildren = {
  AdminAdminPeopleNewRoute: AdminAdminPeopleNewRoute,
  AdminAdminPeopleIndexRoute: AdminAdminPeopleIndexRoute,
}

const AdminAdminPeopleRouteWithChildren =
  AdminAdminPeopleRoute._addFileChildren(AdminAdminPeopleRouteChildren)

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminPeopleRoute: typeof AdminAdminPeopleRouteWithChildren
  AdminAdminPeopleEmployeeIdEditRoute: typeof AdminAdminPeopleEmployeeIdEditRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminPeopleRoute: AdminAdminPeopleRouteWithChildren,
  AdminAdminPeopleEmployeeIdEditRoute: AdminAdminPeopleEmployeeIdEditRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ChartRoute: ChartRoute,
  DirectoryRoute: DirectoryRoute,
  LoginRoute: LoginRoute,
  EmployeeEmployeeIdRoute: EmployeeEmployeeIdRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  JobsSlugRoute: JobsSlugRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  JobsIndexRoute: JobsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
